In [42]:
import pandas as pd

In [43]:
import pandas as pd

data = [
    ["Alice", 23, "Delhi"],
    ["Sneha", 34, "Bhopal"],
    ["Riya", 67, "Indore"]
]

df = pd.DataFrame(data, columns=["name", "age", "city"])

print(df)

    name  age    city
0  Alice   23   Delhi
1  Sneha   34  Bhopal
2   Riya   67  Indore

In [44]:
data={
    "name":["riya","priya","shobha"],
    "age":[23,45,67],
    "city":["bhopal","rewa","bhopal"]
}
df1=pd.DataFrame(data)
df1
df1.set_index('name',inplace=True)
df1

        age    city
name
riya     23  bhopal
priya    45    rewa
shobha   67  bhopal

In [45]:
df.reset_index()

   index   name  age    city
0      0  Alice   23   Delhi
1      1  Sneha   34  Bhopal
2      2   Riya   67  Indore

In [46]:
df=pd.read_csv('data-.csv')
df

    name  age     city category  sales  a   b
0   John   25    Delhi        A    200  5  10
1   Riya   22   Mumbai        B    120  2   3
2   Aman   30     Pune        A    250  7   8
3   Neha   27  Kolkata        C    300  4   6
4  Arjun   35   Jaipur        B    200  1   9

In [47]:
df=pd.read_csv('1_data.csv')
df

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [48]:
df.tail(5)

,order_id,quantity,item_name,choice_description,item_price
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [49]:
df.head(4)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39

In [50]:
df.sample(10)

,order_id,quantity,item_name,choice_description,item_price
4287,1709,1,Steak Soft Tacos,"[Fresh Tomato Salsa, [Cheese, Lettuce]]",$9.25
1865,756,1,Carnitas Salad Bowl,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]",$9.39
1248,509,1,Canned Soft Drink,[Diet Coke],$1.25
4540,1805,1,Chicken Bowl,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",$11.25
2211,891,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Rice, Cheese, Sou...",$8.75
3604,1443,2,Bottled Water,NaN,$3.00
3950,1584,1,Steak Crispy Tacos,"[Fresh Tomato Salsa, [Sour Cream, Lettuce, Ric...",$9.25
4200,1676,1,Canned Soft Drink,[Coke],$1.25
135,60,2,Chicken Salad Bowl,"[Tomatillo Green Chili Salsa, [Sour Cream, Che...",$22.50
1769,714,1,Steak Burrito,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$9.25

In [51]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   str
 3   choice_description  3376 non-null   str
 4   item_price          4622 non-null   str
dtypes: int64(2), str(3)
memory usage: 180.7 KB

In [52]:
df.describe()

          order_id     quantity
count  4622.000000  4622.000000
mean    927.254868     1.075725
std     528.890796     0.410186
min       1.000000     1.000000
25%     477.250000     1.000000
50%     926.000000     1.000000
75%    1393.000000     1.000000
max    1834.000000    15.000000

In [53]:
df.isnull()

      order_id  quantity  item_name  choice_description  item_price
0        False     False      False                True       False
1        False     False      False               False       False
2        False     False      False               False       False
3        False     False      False                True       False
4        False     False      False               False       False
...        ...       ...        ...                 ...         ...
4617     False     False      False               False       False
4618     False     False      False               False       False
4619     False     False      False               False       False
4620     False     False      False               False       False
4621     False     False      False               False       False

[4622 rows x 5 columns]

In [54]:
df.isnull().sum().sum()

np.int64(1246)

In [55]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
4617    False
4618    False
4619    False
4620    False
4621    False
Length: 4622, dtype: bool

In [56]:
df.duplicated().sum()

np.int64(59)

In [57]:
df.rename(columns={'id':'order_id'},inplace=True)
df

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [59]:
df.set_index("order_id",inplace=True)
df

KeyError: "None of ['order_id'] are in the columns"

In [60]:
df

,quantity,item_name,choice_description,item_price
order_id,,,,
1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,Izze,[Clementine],$3.39
1,1,Nantucket Nectar,[Apple],$3.39
1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...
1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [66]:
df['item_name']

order_id
1                Chips and Fresh Tomato Salsa
1                                        Izze
1                            Nantucket Nectar
1       Chips and Tomatillo-Green Chili Salsa
2                                Chicken Bowl
                        ...
1833                            Steak Burrito
1833                            Steak Burrito
1834                       Chicken Salad Bowl
1834                       Chicken Salad Bowl
1834                       Chicken Salad Bowl
Name: item_name, Length: 4622, dtype: str

In [ ]:
df['quantity'].max()

np.int64(15)

In [70]:
df.sum(numeric_only=True)

quantity    4972
dtype: int64

In [71]:
df.mean(numeric_only=True)

quantity    1.075725
dtype: float64